### PR TITLE
Update script.js

### PR DESCRIPTION
**Pull request by btwlouis**
delete some unnecessary code. Not tested

### CODE REVIEW

**Comment by btwlouis** [comment]
never mind. doesn't work

**Comment by ZockerBoysHD** [comment]
yes but i found ur mistake. its line 6. U dont need to close the } and the ) twice. 
After removing line 6  and only leaving line 7 to close it it worked for me

**Comment by ZockerBoysHD** [comment]
can u give me perms and i can edit ur file

**Comment by ZockerBoysHD** [comment]
and then merge it

**Pull request merged**
